### ISSUE TITLE
New animation must cancel existing one

### ISSUE THREAD

**Issue by ojacques** [DMDTools/DOF2DMD#3]
When a request for a new GIF/PNG/movie comes in, it must cancel the rendering of the current one, so that it can be displayed immediately. This also avoids queuing animations, which can last a long time for explosions for example (1942, Galaga).

**Comment by gustavoalara** [comment]
Sorry @ojacques 

I don't understand the issue, the new reworked version currently cancels the previous render to start the new one inmediately. You can check it and validate it
