### ISSUE TITLE
New score from DOFLinx 8.11

### ISSUE THREAD

**Issue by ojacques** [DMDTools/DOF2DMD#6]
> text from exchanges with DDH69:

> With DOFLinx >=8.11, DOFLinx will introduce a new scoring. DOFLinx can monitor up to 2 players (not 4).  The challenge is that DOFLinx has no mean to know how many players there are, until scores start to change. So, in other words, start each game in a score format for 1 player until more players are discovered, then DOFLinx can send the max known players for the life of that game.

Examples:

For 1 player:

1. Game starts, single player
2. `players=1,player=1,score=x`
3. Keep doing 2 until game ends then `players=1,player=1,score=0`

For 2 players: 

1. Game starts, 2 players
2. `players=1,player=1,score=X`
3. Keep doing 2 for first life of P1
4. `players=2,player=2,score=Y`
5. Keep doing 4  for first life of P2
6. `players=2, player=1,score=X`
7. Keep doing 2 for first life of P1
8. `players=2,player=2,score=Y`
9. Keep doing 4  for first life of P2
10. Keep doing 6 - 9 until game ends then `players=1, player=1,score=0`

This is meant to be backward compatible with DOF2DMD original version. 

The intent of this issue is to ensure scoring works the best we can with DOFLinx>=8.11

**Comment by gustavoalara** [comment]
Removed the v2 score board API call and modified the v1 score board API call to add the new DOFLinx Scored Board system

**Comment by ojacques** [comment]
All good.
